export const SET_USER = 'AUTH/SET_USER';
export const SET_TOKEN = 'AUTH/SET_TOKEN';
export const SET_AUTHENTICATED = 'AUTH/AUTHENTICATED';
export const SET_QUESTIONAVALIATION = 'AUTH/QUESTIONAVALIATION';
export const SET_ANSWERS = 'AUTH/ANSWERS';
